### ISSUE TITLE
Not able to find grapheme_break_property.json file while executing

### ISSUE THREAD

**Issue by TianchengTang** [rsalmei/alive-progress#162]
Dear author,

I am trying this alive progress bar it looks awesome! However while running the script, it shows below error. Please note that I only see this issue after converting .py to .exe using "auto-py-to-exe" tool.

Traceback (most recent call last):
  File "build_tree.py", line 486, in <module>
    with alive_bar(len(xml_list), spinner='classic', bar='classic', enrich_print=False) as bar:
  File "alive_progress\core\progress.py", line 106, in alive_bar
  File "alive_progress\core\configuration.py", line 149, in create_context
  File "alive_progress\core\configuration.py", line 183, in lazy_init
  File "alive_progress\core\configuration.py", line 14, in _spinner_input_factory
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "alive_progress\styles\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "alive_progress\styles\exhibit.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "alive_progress\styles\internal.py", line 126, in <module>
  File "alive_progress\styles\internal.py", line 12, in __create_spinners
  File "alive_progress\animations\spinners.py", line 43, in frame_spinner_factory
  File "alive_progress\animations\spinners.py", line 43, in <genexpr>
  File "alive_progress\animations\spinners.py", line 43, in <genexpr>
  File "alive_progress\utils\cells.py", line 145, in to_cells
  File "alive_progress\utils\cells.py", line 149, in split_graphemes
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "grapheme\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "grapheme\api.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "grapheme\finder.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "grapheme\grapheme_property_group.py", line 97, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*myusername*\\AppData\\Local\\Temp\\_MEI11362\\grapheme\\data/grapheme_break_property.json'

Can you please help take a look and provide solution? Appreciate it!

**Comment by TheTechRobo** [comment]
#123

**Comment by rsalmei** [comment]
Thanks man. But please always look for similar issues before asking.
This was already asked and it's a problem with the way you generate your executable. A dependency I use needs a file that was not copied, the issue above explains it.

Thanks @TheTechRobo! 👍

**Comment by TianchengTang** [comment]
Thank you all. I have tried to include extra imports in my program as
mentioned in above ticket but it still doesn't work. My workaround is to
downgrade the library.

Regards,
Kingsley

Rogério Sampaio de Almeida ***@***.***> 于2022年5月6日周五 15:35写道：

**Comment by rsalmei** [comment]
Hey @TianchengTang, I think you misunderstand that issue.
You do not need to include any extra imports in your program, you need to configure your exe maker somehow to tell it to fully include the necessary files.

When it compacts the files needed, it makes an educated guess of which files to include, but in certain cases it guesses it wrong. This is one of these cases: the `grapheme` dependency I use here has to interpret the whole Unicode table, which includes ALL Emoji codes and combinations. This info is not in code, it is in huge files `grapheme` uses, and your exe maker is not including them.

Well, I see you use this `auto-py-to-exe`, you should read its documentation to find out how to correctly configure it to include all files...
I hope it is clearer now 👍

**Comment by rsalmei** [comment]
I just took a look at this [auto-py-to-exe](https://github.com/brentvollebregt/auto-py-to-exe).
Behind the scenes, it does use PyInstaller, the same as used in that issue resolved here. You probably just need to click "Include additional files/folder", and put the same as in this comment: https://github.com/rsalmei/alive-progress/issues/123#issuecomment-1066133372

**Comment by TianchengTang** [comment]
Thanks for detailed information. it works now!

Regards,
Tiancheng

Rogério Sampaio de Almeida ***@***.***> 于2022年5月9日周一 21:27写道：

**Comment by rsalmei** [comment]
I'm glad! 👍
