### ISSUE TITLE
crashes app after build in PyInstaller

### ISSUE THREAD

**Issue by 5nail000** [rsalmei/alive-progress#172]
Traceback (most recent call last):
  File "f_gui.py", line 44, in print_me
  File "f_run_script.py", line 94, in run_script
  File "alive_progress\core\progress.py", line 107, in alive_bar
  File "alive_progress\core\configuration.py", line 149, in create_context
  File "alive_progress\core\configuration.py", line 183, in lazy_init
  File "alive_progress\core\configuration.py", line 14, in _spinner_input_factory
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "alive_progress\styles\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "alive_progress\styles\exhibit.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "alive_progress\styles\internal.py", line 126, in <module>
  File "alive_progress\styles\internal.py", line 12, in __create_spinners
  File "alive_progress\animations\spinners.py", line 43, in frame_spinner_factory
  File "alive_progress\animations\spinners.py", line 43, in <genexpr>
  File "alive_progress\animations\spinners.py", line 43, in <genexpr>
  File "alive_progress\utils\cells.py", line 145, in to_cells
  File "alive_progress\utils\cells.py", line 149, in split_graphemes
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grapheme\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grapheme\api.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grapheme\finder.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "grapheme\grapheme_property_group.py", line 97, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Adm\\AppData\\Local\\Temp\\_MEI30762\\grapheme\\data/grapheme_break_property.json'

**Comment by TheTechRobo** [comment]
Please search through existing issues before creating a new one.

9 issues fit the search criteria "pyinstaller": https://github.com/rsalmei/alive-progress/issues?q=pyinstaller, most are duplicates of #123 (which is the one you want).
