### ISSUE TITLE
cannot use with `dill`

### ISSUE THREAD

**Issue by weaver9651** [rsalmei/alive-progress#217]
Hello. When I use `alive-progress` with `dill` package, an error occurs.
Here's the code that I tried.
```python
import time

import dill
from alive_progress import alive_bar

total_len = 1000
with alive_bar(total_len) as bar:
    for _ in range(0, total_len):
        time.sleep(0.001)
        bar()
```
Please let me know if I missed something.
Thank you.

**Comment by TheTechRobo** [comment]
What error occurs?

**Comment by weaver9651** [comment]
```text
Traceback (most recent call last):
  File "tmp.py", line 7, in <module>
    with alive_bar(total_len) as bar:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/.virtualenvs/tmp/lib/python3.8/site-packages/alive_progress/core/progress.py", line 328, in __alive_bar
    start_monitoring()
  File "/home/user/.virtualenvs/tmp/lib/python3.8/site-packages/alive_progress/core/progress.py", line 190, in start_monitoring
    hook_manager.install()
  File "/home/user/.virtualenvs/tmp/lib/python3.8/site-packages/alive_progress/core/hook_manager.py", line 88, in install
    before_handlers.update({h: h.setStream(get_hook_for(h)) for h in handlers})
  File "/home/user/.virtualenvs/tmp/lib/python3.8/site-packages/alive_progress/core/hook_manager.py", line 88, in <dictcomp>
    before_handlers.update({h: h.setStream(get_hook_for(h)) for h in handlers})
  File "/usr/lib/python3.8/logging/__init__.py", line 1110, in setStream
    self.stream = stream
AttributeError: can't set attribute
```

**Comment by rsalmei** [comment]
Oh boy, `dill`'s author has used a protected `logging` class, which is Python's last resort internal processing... 🤦‍♂️ 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/6652853/210185036-82f7569b-5781-4c6b-97dc-a493af716948.png">

But ok, I think I can ignore errors in there...

**Comment by rsalmei** [comment]
Release 3.0.1 fixes this.
