### ISSUE TITLE
Using the progress without the with statement

### ISSUE THREAD

**Issue by RobinFrcd** [rsalmei/alive-progress#99]
Hello,
I know with statements are great in some cases, but I also like to have my code with as less indents blocks as possible.

Is it possible to use the package without the with statement ? With a wrapper function over the generator I'm looping over.

Thanks!

**Comment by rsalmei** [comment]
Well, I'm going to assume it did work.
Please reopen if anything new arises.

**Comment by RobinFrcd** [comment]
Thank you for your answer!

Sorry for the late reply, I've only been able to test it today, but I've an issue with this version (with both alive_bar and alive_it):

```
Traceback (most recent call last):
  File "training/test_trainer.py", line 33, in <module>
    test_main()
  File "training/test_trainer.py", line 21, in test_main
    params=params,
  File "/Users/rfourcade/dev/research/generation/scoring/offpolicy-network/iktos/offpolicy_network/training/trainer.py", line 93, in main
    with alive_bar(params.nb_epochs, title="Epochs") as bar:
  File "/Users/rfourcade/.pyenv/versions/3.7.9/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/rfourcade/Library/Caches/pypoetry/virtualenvs/iktos-offpolicy-network-Oz28eVis-py3.7/lib/python3.7/site-packages/alive_progress/core/progress.py", line 247, in __alive_bar
    start_monitoring()
  File "/Users/rfourcade/Library/Caches/pypoetry/virtualenvs/iktos-offpolicy-network-Oz28eVis-py3.7/lib/python3.7/site-packages/alive_progress/core/progress.py", line 144, in start_monitoring
    hook_manager.install()
  File "/Users/rfourcade/Library/Caches/pypoetry/virtualenvs/iktos-offpolicy-network-Oz28eVis-py3.7/lib/python3.7/site-packages/alive_progress/core/hook_manager.py", line 66, in install
    for h in root.handlers if isinstance(h, StreamHandler)})
  File "/Users/rfourcade/Library/Caches/pypoetry/virtualenvs/iktos-offpolicy-network-Oz28eVis-py3.7/lib/python3.7/site-packages/alive_progress/core/hook_manager.py", line 66, in <dictcomp>
    for h in root.handlers if isinstance(h, StreamHandler)})
  File "/Users/rfourcade/Library/Caches/pypoetry/virtualenvs/iktos-offpolicy-network-Oz28eVis-py3.7/lib/python3.7/site-packages/alive_progress/core/hook_manager.py", line 96, in _set_stream
    return handler.setStream(stream)
  File "/Users/rfourcade/.pyenv/versions/3.7.9/lib/python3.7/logging/__init__.py", line 1050, in setStream
    self.stream = stream
AttributeError: can't set attribute
```

Is it a known bug in this version ? Thanks

**Comment by rsalmei** [comment]
No problem, you're welcome.

But wow, that's very weird.
This error is for when one tries to set a `@property` which has no setter.
But `stream` is a ordinary field there.

Can you please write a minimal code that triggers this error?
Did you use `python` or `ipython`?

**Comment by RobinFrcd** [comment]
My company uses a custom logger wrapper. I just realized this bug happens only when I'm using this custom logger and not the vanilla one.

I guess I'll have to take a look at our own logger then! Thanks!

**Comment by rsalmei** [comment]
Wow, that's it.
Unfortunately it is a bad implementation this coloredlogs... I found it:
https://github.com/xolox/python-coloredlogs/blob/master/coloredlogs/__init__.py#L1336-L1337

Since Python 3.7, StreamHandler has this [setStream](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler.setStream) method, and that implementation simply breaks it...

On a quick look, you should try to avoid that coloredlogs' `StandardErrorHandler` to be installed. It seems the easiest way is to not use `stderr` in the first place. Try to send your logs to `stdout`, or disable it any other way.

**Comment by RobinFrcd** [comment]
The thing is I need this stderr too. I've opened [an issue](https://github.com/xolox/python-coloredlogs/issues/106), I hope it'll be fixed soon. Otherwise, I'll make my own fork or use [colorlog](https://pypi.org/project/colorlog/) I guess.

Anyway, thanks for the help here ! The issue has nothing to do with `alive-progress` so I guess we can close it.

**Comment by rsalmei** [comment]
Nice, hope they fix that.
But this other `colorlog` seems way less invasive.
You're welcome man!
